paths:
  raw_dir: "data/raw_seq"
  filtered_dir: "data/filtered"
  qc_dir: "results/outputs/qc"
  html_dir: "results/results_docs"
#mapping
  ref_dir: "data/reference"
  mapping_dir: "results/outputs/mapping"
qc:
  threads: 20
  min_length: 500
  min_mean_q: 12
mapping:
  threads: 20
  extra_options: "--secondary=no"
  hosts:
    - mutuki
    - grandis