name: render_rmd_pdf
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - r-base=4.2
    - r-rmarkdown
    - r-knitr
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-kableextra
    - weasyprint
    - pandoc
